version: "3.7"

services:
  mysql:
    image: mysql:8
    restart: always
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_TCP_PORT: 3309
    ports:
      - "3309:3309"
    expose:
      - "3309"
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./mysql-init.sql:/tmp/mysql-init.sql
    command: --sort_buffer_size=512K

volumes:
  mysql-data:
    external: false